//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDay
    {
        public int TaskDaysId { get; set; }
        public string TaskDaysValue { get; set; }
        public Nullable<int> UserTaskId { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
