//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTask()
        {
            this.TaskDays = new HashSet<TaskDay>();
            this.UserAlertReports = new HashSet<UserAlertReport>();
            this.UserTaskAlerts = new HashSet<UserTaskAlert>();
        }
    
        public int UserTaskId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TaskTypesId { get; set; }
        public string UserTaskTitle { get; set; }
        public string UserTaskComments { get; set; }
        public string UserTaskLink { get; set; }
        public string UserTaskImage { get; set; }
        public Nullable<System.DateTime> UserTaskDate { get; set; }
        public Nullable<System.TimeSpan> UserTaskStartTime { get; set; }
        public Nullable<System.TimeSpan> UserTaskEndTime { get; set; }
        public string UserTaskDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDay> TaskDays { get; set; }
        public virtual TaskType TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAlertReport> UserAlertReports { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTaskAlert> UserTaskAlerts { get; set; }
    }
}
