//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAlertReport
    {
        public int UserAlertReportId { get; set; }
        public Nullable<int> UserTaskId { get; set; }
        public Nullable<System.DateTime> UserAlertReportDate { get; set; }
        public Nullable<bool> UserAlertReportStatus { get; set; }
        public string UserAlertReportType { get; set; }
        public Nullable<int> UserAlertReportMinutes { get; set; }
    
        public virtual UserTask UserTask { get; set; }
    }
}
